<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'behavior-pubsub-events-table.js' => 'dd4451ef',
  ),
  'symbols' => array(
    'javelin-behavior-pubsub-events-table' => 'dd4451ef',
  ),
  'requires' => array(),
  'packages' => array(),
);
