<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PubSubAPIController' => 'controller/PubSubApiController.php',
    'PubSubApplication' => 'application/PubSubApplication.php',
    'PubSubController' => 'controller/PubSubController.php',
    'PubSubEditController' => 'controller/PubSubEditController.php',
    'PubSubFeedController' => 'controller/PubSubFeedController.php',
    'PubSubListController' => 'controller/PubSubListController.php',
    'PubSubQuery' => 'query/PubSubQuery.php',
    'Subscriber' => 'lib/Subscriber.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PubSubAPIController' => 'PhabricatorConduitController',
    'PubSubApplication' => 'PhabricatorApplication',
    'PubSubController' => 'PhabricatorController',
    'PubSubEditController' => 'PubSubController',
    'PubSubFeedController' => 'PubSubController',
    'PubSubListController' => 'PubSubController',
    'PubSubQuery' => 'PhabricatorCursorPagedPolicyAwareQuery',
  ),
));
