<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CelerityPubSubResources' => 'celerity/CelerityPubSubResources.php',
    'PubSubAPIController' => 'controller/PubSubApiController.php',
    'PubSubApplication' => 'application/PubSubApplication.php',
    'PubSubConduitAPIMethod' => 'conduit/PubSubConduitAPIMethod.php',
    'PubSubConstants' => 'constants/PubSubConstants.php',
    'PubSubController' => 'controller/PubSubController.php',
    'PubSubDAO' => 'storage/PubSubDAO.php',
    'PubSubEditController' => 'controller/PubSubEditController.php',
    'PubSubEventController' => 'controller/PubSubEventController.php',
    'PubSubEventData' => 'storage/PubSubEventData.php',
    'PubSubEventDataProvider' => 'storage/PubSubEventDataProvider.php',
    'PubSubEventField' => 'customfield/PubHubEventField.php',
    'PubSubEventQuery' => 'query/PubSubEventQuery.php',
    'PubSubEventTableView' => 'views/PubSubEventTableView.php',
    'PubSubFeedStory' => 'transactions/PubSubFeedStory.php',
    'PubSubListController' => 'controller/PubSubListController.php',
    'PubSubProjectCustomField' => 'customfield/PubSubProjectCustomField.php',
    'PubSubQuery' => 'query/PubSubQuery.php',
    'PubSubResponse' => 'config/PubSubResponse.php',
    'PubSubSetEventConduitAPIMethod' => 'conduit/PubSubSetEventConduitAPIMethod.php',
  ),
  'function' => array(),
  'xmap' => array(
    'CelerityPubSubResources' => 'CelerityResourcesOnDisk',
    'PubSubAPIController' => 'PhabricatorConduitController',
    'PubSubApplication' => 'PhabricatorApplication',
    'PubSubConduitAPIMethod' => 'ConduitAPIMethod',
    'PubSubController' => 'PhabricatorController',
    'PubSubDAO' => 'PhabricatorLiskDAO',
    'PubSubEditController' => 'PubSubController',
    'PubSubEventController' => 'PubSubController',
    'PubSubEventData' => array(
      'PhabricatorProjectDAO',
      'PhabricatorApplicationTransactionInterface',
    ),
    'PubSubEventField' => 'PubSubProjectCustomField',
    'PubSubEventQuery' => 'PubSubDAO',
    'PubSubEventTableView' => 'Phobject',
    'PubSubFeedStory' => 'PhabricatorFeedStory',
    'PubSubListController' => 'PubSubController',
    'PubSubProjectCustomField' => array(
      'PhabricatorProjectCustomField',
      'PhabricatorStandardCustomFieldInterface',
    ),
    'PubSubQuery' => 'PhabricatorCursorPagedPolicyAwareQuery',
    'PubSubResponse' => 'AphrontStandaloneHTMLResponse',
    'PubSubSetEventConduitAPIMethod' => 'PubSubConduitAPIMethod',
  ),
));
